### ISSUE TITLE
duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by yhakamay** [yhakamay/cub3d#24]
`duplicate symbols for architecture x86_64` が `g_num_rays`, `g_wall_strip_width` で発生する

**Comment by yhakamay** [comment]
■ チェック項目
- [ ] 別のところで再定義していないか？
- [ ] `cub3d.h` を二重インクルードしていないか？
- [ ] インクルードするライブラリで定義されている変数名と重複していないか？

参考: https://marycore.jp/prog/xcode/duplicate-symbols-for-architecture-x86_64/

**Comment by mhatsu** [comment]
原因: cub3d.hファイルは全ての.cファイルで読み込まれるが、cub3d.hでglobal変数を「定義」してしまっていたため、.cファイルに読み込まれる度にglobal変数が定義されてしまっていた。

解決法：cub3d.hでは"extern"を用いてglobal変数の「宣言」のみをするようにした。global変数の「定義」はcub3d_utils.cで行うようにした。

参考：https://monozukuri-c.com/langc-funclist-extern/#toc1
