### ISSUE TITLE
テクスチャの画質が荒い

### ISSUE THREAD

**Issue by mhatsu** [yhakamay/cub3d#28]
テクスチャの画質が荒い気がする。おそらく、xpmのイメージから壁にrenderするときに、無理やり大きさを合わせてるのがよくないと思う。

**Comment by mhatsu** [comment]
lodevの画像でやったら、なんかこれでもいい気がしてきた

**Comment by yhakamay** [comment]
@mhatsu よさそうやね！！ありがとう 👍
