### ISSUE TITLE
壁の衝突時にセグる

### ISSUE THREAD

**Issue by yhakamay** [yhakamay/cub3d#31]
発生頻度は稀。`ray.distance == 0`（つまり `(player.x, player.y) == (wall.x, wall.y)`）の時。

**Comment by yhakamay** [comment]
対症療法だけど、`player` が 壁の手前まで（たとえば10pxとか）しか進めないようにします

**Comment by yhakamay** [comment]
👆 どうにもうまくいかなかったので、以下の1文追加するだけに留まってます。セグフォはしなくなった代わりに、壁と接触したタイミングで画面全体がボーダーで覆われる… 何かアイデアあれば教えて 😢 @mhatsu 

```c
correct_wall_distance = correct_wall_distance == 0 ? 3.0 : correct_wall_distance;
```
![border](https://user-images.githubusercontent.com/65002858/112661257-ac7dd400-8e99-11eb-896a-5e4aa0bc5fb2.gif)

**Comment by mhatsu** [comment]
んー、今のところいいアイデアは思い浮かんできやせん。やっぱり進行方向に応じて、has_wall_atを改良するのが一番なのかも

**Comment by yhakamay** [comment]
おけ、もーちょい粘ります…

**Comment by yhakamay** [comment]
解決した！`player` のspawn位置を1pxずつずらしたら、20の倍数にならなくなりました 🎉 

```diff
void		check_map_info(t_params *params)
{
	[...]    
-				params->player.x = (j + 0.5) * TILE_SIZE;
-				params->player.y = (i + 0.5) * TILE_SIZE;
+				params->player.x = (j + 0.5) * TILE_SIZE + 1;
+				params->player.y = (i + 0.5) * TILE_SIZE + 1;
				params->map.grid[i][j] = '0';
	[...]
}
```
